theme = "catppuccin_mocha"

[editor]
auto-completion = true
bufferline = "multiple"
line-number = "relative"

[keys.normal]
esc = ["collapse_selection", "normal_mode"]
w = ["move_next_word_start", "collapse_selection"]
b = ["move_prev_word_start", "collapse_selection"]
e = ["move_prev_word_end", "collapse_selection"]
a = ["append_mode", "collapse_selection"]
x = ["delete_selection"]
d.d = ["extend_to_line_bounds", "delete_selection"]
"C-h" = ["goto_previous_buffer"]
"C-l" = ["goto_next_buffer"]

[keys.select]
x = ["delete_selection"]
d.d = ["extend_to_line_bounds", "delete_selection"]

[keys.insert]
"C-h" = ["goto_previous_buffer"]
"C-l" = ["goto_next_buffer"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.inline-diagnostics]
cursor-line = "warning"
other-lines = "error"

[editor.lsp]
display-inlay-hints = true

[editor.statusline]
center = ["file-name"]
left = ["mode", "spinner"]
right = [
    "diagnostics",
    "selections",
    "position",
    "file-encoding",
    "file-line-ending",
    "file-type",
]
separator = "â”‚"

[editor.statusline.mode]
insert = "INSERT"
normal = "NORMAL"
select = "SELECT"
